# External gems
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
gems:
  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - "/vendor/"

# Site settings
title: Chi-Jen Roger Lo
subtitle: "PhD student @ University of Cambridge"
email: intelisef47@gmail.com
name: Lo Chi-Jen
description: > PhD student @ University of Cambridge
# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
cover: "/assets/header_image.jpg"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: false
highlightjs_theme: "monokai-sublime"

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# Disqus comments
disqus_shortname: rogerlo47

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
social:
  - name: Instagram
    icon: instagram
    username: rogerlo47
    url: https://www.instagram.com/rogerlo47/
    desc: Follow me on Instagram
    share: true

  - name: GitHub
    icon: github
    username: RogerLo47
    url: https://github.com/RogerLo47
    desc: Fork me on GitHub
    share: true

  - name: Facebook
    icon: facebook
    username: Chi-Jen Roger Lo
    url: https://www.facebook.com/roger.lo.47.81
    desc: Friend me on Facebook
    share: true

  - name: LinkedIn
    icon: linkedin
    username: Chi-Jen Roger Lo
    url: https://www.linkedin.com/in/rogerlo47/
    desc: Connect with me on LinkedIn
    share: true

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "/assets/logo.png"

    os_repo: ""
    os_rcs_type: ""
    os_src: ""
